In [ ]:
import pandas as pd

df = pd.read_csv("hf://datasets/lukebarousse/data_jobs/data_jobs.csv")
df2 = pd.read_csv("../Data/processed/job_market_processed_data.csv")

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 785741 entries, 0 to 785740
Data columns (total 17 columns):
 #   Column                 Non-Null Count   Dtype
---  ------                 --------------   -----
 0   job_title_short        785741 non-null  object
 1   job_title              785740 non-null  object
 2   job_location           784696 non-null  object
 3   job_via                785733 non-null  object
 4   job_schedule_type      773074 non-null  object
 5   job_work_from_home     785741 non-null  bool
 6   search_location        785741 non-null  object
 7   job_posted_date        785741 non-null  object
 8   job_no_degree_mention  785741 non-null  bool
 9   job_health_insurance   785741 non-null  bool
 10  job_country            785692 non-null  object
 11  salary_rate            33067 non-null   object
 12  salary_year_avg        22003 non-null   float64
 13  salary_hour_avg        10662 non-null   float64
 14  company_name           785723 non-null  object
 15  job_skills             668704 non-null  object
 16  job_type_skills        668704 non-null  object
dtypes: bool(3), float64(2), object(12)
memory usage: 86.2+ MB

In [8]:
df

,job_title_short,job_title,job_location,job_via,job_schedule_type,job_work_from_home,search_location,job_posted_date,job_no_degree_mention,job_health_insurance,job_country,salary_rate,salary_year_avg,salary_hour_avg,company_name,job_skills,job_type_skills
0,Senior Data Engineer,Senior Clinical Data Engineer / Principal Clin...,"Watertown, CT",via Work Nearby,Full-time,False,"Texas, United States",2023-06-16 13:44:15,False,False,United States,NaN,NaN,NaN,Boehringer Ingelheim,NaN,NaN
1,Data Analyst,Data Analyst,"Guadalajara, Jalisco, Mexico",via BeBee México,Full-time,False,Mexico,2023-01-14 13:18:07,False,False,Mexico,NaN,NaN,NaN,Hewlett Packard Enterprise,"['r', 'python', 'sql', 'nosql', 'power bi', 't...","{'analyst_tools': ['power bi', 'tableau'], 'pr..."
2,Data Engineer,"Data Engineer/Scientist/Analyst, Mid or Senior...","Berlin, Germany",via LinkedIn,Full-time,False,Germany,2023-10-10 13:14:55,False,False,Germany,NaN,NaN,NaN,ALPHA Augmented Services,"['python', 'sql', 'c#', 'azure', 'airflow', 'd...","{'analyst_tools': ['dax'], 'cloud': ['azure'],..."
3,Data Engineer,LEAD ENGINEER - PRINCIPAL ANALYST - PRINCIPAL ...,"San Antonio, TX",via Diversity.com,Full-time,False,"Texas, United States",2023-07-04 13:01:41,True,False,United States,NaN,NaN,NaN,Southwest Research Institute,"['python', 'c++', 'java', 'matlab', 'aws', 'te...","{'cloud': ['aws'], 'libraries': ['tensorflow',..."
4,Data Engineer,Data Engineer- Sr Jobs,"Washington, DC",via Clearance Jobs,Full-time,False,Sudan,2023-08-07 14:29:36,False,False,Sudan,NaN,NaN,NaN,Kristina Daniel,"['bash', 'python', 'oracle', 'aws', 'ansible',...","{'cloud': ['oracle', 'aws'], 'other': ['ansibl..."
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
785736,Software Engineer,DevOps Engineer,Singapura,melalui Trabajo.org,Pekerjaan tetap,False,Singapore,2023-03-13 06:16:16,False,False,Singapore,NaN,NaN,NaN,CAREERSTAR INTERNATIONAL PTE. LTD.,"['bash', 'python', 'perl', 'linux', 'unix', 'k...","{'os': ['linux', 'unix'], 'other': ['kubernete..."
785737,Data Analyst,CRM Data Analyst,"Bad Rodach, Jerman",melalui BeBee Deutschland,Pekerjaan tetap,False,Germany,2023-03-12 06:18:18,False,False,Germany,NaN,NaN,NaN,HABA FAMILYGROUP,"['sas', 'sas', 'sql', 'excel']","{'analyst_tools': ['sas', 'excel'], 'programmi..."
785738,Business Analyst,Commercial Analyst - Start Now,Malaysia,melalui Ricebowl,Pekerjaan tetap,False,Malaysia,2023-03-12 06:32:36,False,False,Malaysia,NaN,NaN,NaN,Lendlease Corporation,"['powerpoint', 'excel']","{'analyst_tools': ['powerpoint', 'excel']}"
785739,Data Engineer,"Principal Associate, Data Engineer (Remote-Eli...","Newark, New Jersey, Amerika Serikat",melalui Recruit.net,Pekerjaan tetap,False,Sudan,2023-03-12 06:32:15,False,False,Sudan,NaN,NaN,NaN,Capital One,"['python', 'go', 'nosql', 'sql', 'mongo', 'she...","{'cloud': ['aws', 'snowflake', 'azure', 'redsh..."
785740,Software Engineer,AWS System Analyst,India,melalui Trigyn,Pekerjaan tetap,False,India,2023-03-13 06:16:31,False,False,India,NaN,NaN,NaN,Trigyn,"['aws', 'flow']","{'cloud': ['aws'], 'other': ['flow']}"

In [6]:
df2.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45241 entries, 0 to 45240
Data columns (total 14 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   Title              45220 non-null  object
 1   Location           45241 non-null  object
 2   Company            45241 non-null  object
 3   Job_Type           45241 non-null  object
 4   Salary             24556 non-null  object
 5   description_clean  22366 non-null  object
 6   min_salary         24379 non-null  float64
 7   max_salary         24379 non-null  float64
 8   avg_salary         24379 non-null  float64
 9   has_salary         45241 non-null  bool
 10  has_description    45241 non-null  bool
 11  city               45241 non-null  object
 12  state              45126 non-null  object
 13  country            45241 non-null  object
dtypes: bool(2), float64(3), object(9)
memory usage: 4.2+ MB

In [7]:
df2

,Title,Location,Company,Job_Type,Salary,description_clean,min_salary,max_salary,avg_salary,has_salary,has_description,city,state,country
0,Cybersecurity Systems Engineer,"Des Plaines, IL","Kranze Technology Solutions, Inc",Full-time,NaN,NaN,NaN,NaN,NaN,False,False,Des Plaines,IL,United States
1,Staff Software Engineer,"Skokie, IL",Jobot,Full-time,$130K - $190K / yr,NaN,130000.0,190000.0,160000.0,True,False,Skokie,IL,United States
2,Software Development Team Lead,"Burr Ridge, IL","Uline, Inc.",Full-time,NaN,NaN,NaN,NaN,NaN,False,False,Burr Ridge,IL,United States
3,Lead Software Engineer - Full Stack - Java/Rea...,"Chicago, IL",JPMorganChase,Full-time,NaN,NaN,NaN,NaN,NaN,False,False,Chicago,IL,United States
4,CNC Manufacturing Engineer,"Chicago, IL",Aegis Worldwide,Full-time,$90K - $105K / yr,NaN,90000.0,105000.0,97500.0,True,False,Chicago,IL,United States
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
45236,Technical Projet Manager (AWS DevOps),"Chicago, IL",ProIT Inc.,Contract,$55 - $60 an hour,NaN,114400.0,124800.0,119600.0,True,False,Chicago,IL,United States
45237,Sr Manager -IT App Dev Fuel Management,"Chicago, IL",United Airlines,Full-time,"$137,275 - $187,000 a year",NaN,137275.0,187000.0,162137.5,True,False,Chicago,IL,United States
45238,Senior DevSecOps Engineer/RPA Senior Product E...,"Chicago, IL","Professional Solutions Delivered, LLC",unknown,"$125,000 - $140,000 a year",NaN,125000.0,140000.0,132500.0,True,False,Chicago,IL,United States
45239,"VP, AWS Cloud Architect","Chicago, IL",Synchrony,unknown,"$130,000 - $210,000 a year",NaN,130000.0,210000.0,170000.0,True,False,Chicago,IL,United States
45240,Solutions Architect III - AWS,"Chicago, IL",Tek Ninjas,Contract,Estimated: $135K - $171K a year,NaN,135000.0,171000.0,153000.0,True,False,Chicago,IL,United States

In [ ]:
df2.rename(columns={"Title":"job_title", "Location":"job_location", "Company":"job_company", "Job_Type":"job_schedule_type", "country":"job_country", "avg_salary":"salary_avg"}, inplace=True)

In [15]:
df2.columns

Index(['job_title', 'job_location', 'job_company', 'job_schedule_type',
       'Salary', 'description_clean', 'min_salary', 'max_salary', 'salary_avg',
       'has_salary', 'has_description', 'city', 'state', 'job_country',
       'skills', 'job_skills'],
      dtype='object')

In [22]:
df["job_title"].value_counts()

job_title
Data Engineer                                          53908
Data Scientist                                         42542
Data Analyst                                           41950
Senior Data Engineer                                   20217
Senior Data Scientist                                  13335
                                                       ...
Senior Semantic Data Engineer                              1
Data Scientist- Mid Level - Now Hiring                     1
Engineering Service Manager (Data Center Operation)        1
Data Engineer(5+yrs)                                       1
Data Engineering Lead Architect                            1
Name: count, Length: 234673, dtype: int64

In [23]:
df2["job_title"].value_counts()

job_title
Senior Software Engineer                                       2566
Software Engineer                                              1328
Full Stack Developer                                            652
Full Stack Engineer                                             528
Web Developer                                                   526
                                                               ...
Software Developers, Java                                         1
Software Developer BI Lead                                        1
Java Developers                                                   1
Distribution Automation Maintenance & Support Engineer            1
Senior Manager - IT Application Development Fuel Management       1
Name: count, Length: 2853, dtype: int64

In [25]:
df.to_csv("../Data/merger/data_jobs.csv", index=False)
df2.to_csv("../Data/merger/job_market_processed_data.csv", index=False)